# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

resources:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'reg-dev-ranz-devtier1 (SPN)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group list'

  - task: Packer@1
  inputs:
    connectedServiceType: 'azure'
    azureSubscription: 'reg-dev-ranz-devtier1 (SPN)'
    command: 'build'

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'

- task: Ansible@0
  inputs:
    ansibleInterface: 'agentMachine'
    inventoriesAgentMachine: 'noInventory'

